// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemporaryProjects
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNewTempProjectCommandPackageString = "5abd62ee-e60e-45a5-bd01-9c873436490f";
        public const string guidNewTempProjectCommandPackageCmdSetString = "f5e2d15e-a980-4a05-81ec-fda9c6f91a9c";
        public static Guid guidNewTempProjectCommandPackage = new Guid(guidNewTempProjectCommandPackageString);
        public static Guid guidNewTempProjectCommandPackageCmdSet = new Guid(guidNewTempProjectCommandPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NewTempProjectCommandId = 0x0100;
    }
}
