// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemporaryProjects
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string newTempProjectCommandPackageString = "5abd62ee-e60e-45a5-bd01-9c873436490f";
        public const string startPageExtenderPackageString = "4192762b-3595-46c9-96ea-09da3040410b";
        public const string getToCodeExtenderPackageString = "25f9a43d-c98c-45f1-9741-cc423c1ef5ea";
        public const string startPageToolWindowString = "387cb18d-6153-4156-9257-9ac3f9207bbe";
        public const string guidNewTempProjectCommandPackageCmdSetString = "f5e2d15e-a980-4a05-81ec-fda9c6f91a9c";
        public static Guid newTempProjectCommandPackage = new Guid(newTempProjectCommandPackageString);
        public static Guid startPageExtenderPackage = new Guid(startPageExtenderPackageString);
        public static Guid getToCodeExtenderPackage = new Guid(getToCodeExtenderPackageString);
        public static Guid startPageToolWindow = new Guid(startPageToolWindowString);
        public static Guid guidNewTempProjectCommandPackageCmdSet = new Guid(guidNewTempProjectCommandPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NewTempProjectCommandId = 0x0100;
    }
}
